export const COMMON_ICONS = [
  { emoji: "🏠", label: "Home" },
  { emoji: "🚗", label: "Automotive" },
  { emoji: "💻", label: "Technology" },
  { emoji: "🛠️", label: "Repair" },
  { emoji: "🧹", label: "Cleaning" },
  { emoji: "🎨", label: "Art & Design" },
  { emoji: "📱", label: "Mobile" },
  { emoji: "🍽️", label: "Food & Dining" },
  { emoji: "👔", label: "Professional" },
  { emoji: "💄", label: "Beauty" },
  { emoji: "🌱", label: "Garden" },
  { emoji: "🏋️", label: "Fitness" },
  { emoji: "📚", label: "Education" },
  { emoji: "🎵", label: "Music" },
  { emoji: "📷", label: "Photography" },
  { emoji: "✈️", label: "Travel" },
  { emoji: "🏥", label: "Healthcare" },
  { emoji: "⚖️", label: "Legal" },
  { emoji: "💰", label: "Finance" },
  { emoji: "🎯", label: "Marketing" },
  { emoji: "🔧", label: "Tools" },
  { emoji: "🛡️", label: "Security" },
  { emoji: "📊", label: "Analytics" },
  { emoji: "🎭", label: "Entertainment" },
];